apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ibm-entitlement-key
  namespace: cp4i-apic
spec:
  encryptedData:
    .dockerconfigjson: AgBrlXipUGRRAJZhq7rkQ5SjTNWY7rfDGOPPy55McBcnmlXz7bWSWAynm0sM5wakIDzniluIv8sP2uBuLaFcNabd44nZWn04+dr15AA2HK7qER/ESL8bMoB/5nOTLQddiYX2lXqR8kuffb9y7YPcZracKUXrrE7BvmjaN4EaPCBgHuLdNoxkblcXf3ntqlV8XEvNbU8R+vOkfnmIxdCa0gkUMw5I9j6fzbvEcysACse4ccdFskKwzUf96XOeHTlmDAQXugEeKkeB6ZO3GRwUTs5MAfZ1d2Nbes+Smm6y5UpJ6gFMxdr1OQ7nTYW+GvnFFJdSugj9+971jTTatmOT8iBSrSyVEbLXAk7SycLSyctMRf7MRHX0Wqx1pWIrESA+/dbprj3gK7oqWK8kcjQhASf/oNODE5UNyFLv0x+sKr+Zyj1oJcekMrESP8s5iVcL3uBE24//aa9WiAWbjSalhyORk9BrnJghdSjbS0avSgTbQose+ARGihaF1ErpHeZLOyPW6OPPVQJOYPY1PKHqE3n7R9SKpuhpgErkFZQ+pDUrJdQvz64BNsTkoCsZ4sTV6TIm0094HvPUeml9i5EZYigupNe+t32DaCXgfTE5eUXHwnzhm1QVmSemlfC0avXoNnv0y00Xs+gDrmLlE5iK9/mUYvfSL9lEi3kESAQ3KKD8ZE7ROB/vSJGQd6ZQ1A78iA1a6HwnjkDbG1ryAxVOUP5xz8Rzk2rOK6aHRlm6R4xznUGtc4+AnZZD0y6QAOKgT+/+UxxsSneId16v6eP4mIPkE3EIwysjTdtpMm005LGRcOfux0e3ZK6fm6CfnL/n8W1ZtrNdLmp1WSLF/nRpqui8LHi/FP7ERHuiOEV/ilVGk8rRKsmu6RY8ZZkouLk3ngOX2CG22dLV9tUwMpxw8+G5p0mmNruyelaxzpcP3kY243MG7X+hghx9XHS95XJg/WNCCDpFf2wZ/pfQ69EiWgstgQ17MJmqghIOO8HE2ti+TY77ukC8bMLerYOWvoWl0PchXpS0igV7xCf1lhrqhwrI0s/J1y8Cg7ul6rmpNja+l+e20PjmCqSQEKejrLQCZVUwz0wR6qYivrEenPirKH8TJ0LGa0ti5Bmc1sLJcj9zultu/QiePU3/VJ1z5mNNshavcP2ecgNvAjqMup+oUdIFoRS+4+z+BawglSU/t1votWTgGeYRk7ahzBsoBbo30L5AlvAAfjXOQhCsSXXSxBq97itvDsp8+IJwPHG+LnSmuY0DQA2lOUnlo91QDMilpzIAh6e2LTJz34U42yKJtVlq3rgHAoUSbBkX46U4h5HjSA7sQPuoWiBHqzNhBrbXVmv3
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: ibm-entitlement-key
      namespace: cp4i-apic
    type: kubernetes.io/dockerconfigjson

