apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ibm-entitlement-key
  namespace: cp4i-apic
spec:
  encryptedData:
    .dockerconfigjson: AgAQi+nLT0MZDt+0FjelqaSGzLs11pxH+ltmaITKHj7CiwXKKlagW99yllnXG3JfdXT266hSe0+5o3ifTvnNArLHJDiZlTVbq3EFBxvA8mq60FG25ajSfcgQXEctIB9a6qrm3h1fiC7DvDVeAvjTyC5AkP5mWRJsxZCWOHHbMdqWw8vjG6Iv3QxxXhYaaNMYGNksV3SvWrlbskBZ6tgNmmlOZuTgqesym/1/HrUWb367Z7+lVdXGDQOKXvBESxkNe5dVP7Y/3qQLvVw4srAohVgw95GFvr8lxpWTPFUyHCeqhaCnGdBmaGyr6Ba+Yxd4hPWhfn2j/uiCRJA/z0VDZcW7oRMniOXDVaWsX3f6c1MMnW34q0wAAx+XcNBidB0tTFvAQ2NXyai9tFTjFnVBSzoNLhM4W5TOgjMcbYhqV7RRWsWNb5DvOxGNThKhpEs4UFg+CYs47wbV3OXFfiYW1UPW4nsoTa9kFnQQ3aN2U3PGoIUiQfBG7/NrALvR26/GkHIy0ceOtMsuFHOj08OHsiI+VhB+nsribDDzePQCv4pMyBJGRA1jUlKCtCmMNgOZPntG1prlelLmOMstCSM/Uvhbfq1HuRZ3qduLqa8Pi0XCCFeBXbS5roIqLVMYTjGkbR7CGs3e5FmHCsrymAHTN+Q+vg97WOaW+sbsY4DpZFN10DaUs1uyrlagiOuUCxYB+w9Z5E5UQqA12dgpttDjAa/O/Y6M/C81ZYdMjB7sTzmPLJchanWEPNGgEI0IiVXTvREvO6+41T1kR+thwzuiw6ZgwHvEd/vM6nWLJTu4RayEzr2zK8z1SkTVT4BKJyOGyExpTsSUffW5V1Lfh3E+Pg8JQMFXuh04hDmZ77hlkrt2gjQF2SB5oeRf2GetozXcNdz2MLIECG1rNVBA5fEXvl3N3vOXKgMPbv/Sl9kxi+mFatMGVHYmI6WyD79F4tF/orb37n+OmzhCHPZvunN78eChalnFco03s4XlEsn+PwstvcO60E6b4UF+Y/hFop4ZLjJMBQr6dPhdunKk/rzhQjqOifqTVDA/lDU4Sk/mHaqGl7JErRTM/xCjQzVPhyh3Z6NAxDyf/aJe2ZDcjR+KE/KAXUgp6Vv+j0Gmbes8kwHnAtneWAIk7V2ZQIr/BPr1YJ5SVbdVq4+K1g5XvLVz/6mRErqAq6Jd3Op+nkzhGOorluCOLGZcuxMqWYI45gbo+ZKJ/zudbegV7by0/Iy7FX5LY6tX1Y3puLFTBY6f5q4kv6IzOed1moRIIIM0mhXm/+4zjCH6uXhDMuEDue3QuWYoBURKFBEcbUuhwA0nKdvqT5wVmZ2KafoGRktFit6zY/wg
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: ibm-entitlement-key
      namespace: cp4i-apic
    type: kubernetes.io/dockerconfigjson

